name: Playwright Tests
on:
  #push:
    #branches: [ main, master ]
  #pull_request:
    #branches: [ main, master ]
  workflow_dispatch:
    inputs:
      ENV:
        description: 'Environment name'
        required: true
        default: 'prod'
        type: choice
        options:
          - dev
          - prod
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
      working-directory: e2e-playwright
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      working-directory: e2e-playwright
    - name: Run Playwright tests
      run: npx playwright test
      working-directory: e2e-playwright
      env:
          ENV: ${{ github.event.inputs.ENV }}
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: e2e-playwright/playwright-report/
        retention-days: 30
